import { useState } from "react";

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Database } from "lucide-react";

import { useAutoGenerateRecords } from "@/hooks/use-records";

interface AutoGenerateDialogProps {
  orgSlug: string;
  projectSlug: string;
  schemaSlug: string;
}

export function AutoGenerateDialog({
  orgSlug,
  projectSlug,
  schemaSlug,
}: AutoGenerateDialogProps) {
  const [open, setOpen] = useState(false);
  const [count, setCount] = useState(10);

  const { mutate, isPending } = useAutoGenerateRecords();

  const handleGenerate = () => {
    mutate(
      {
        orgSlug,
        projectSlug,
        schemaSlug,
        count,
      },
      {
        onSuccess: () => {
          setOpen(false);
          setCount(10);
        },
      }
    );
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="secondary">
          <Database className="mr-2 h-4 w-4" />
          Auto Generate
        </Button>
      </DialogTrigger>

      <DialogContent>
        <DialogHeader>
          <DialogTitle>Auto Generate Records</DialogTitle>

          <DialogDescription>
            Enter the number of mock records to generate.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-2">
          <label className="text-sm font-medium">
            Number of Records
          </label>

          <Input
            type="number"
            min={1}
            value={count}
            onChange={(e) => setCount(Number(e.target.value))}
          />
        </div>

        <DialogFooter>
          <Button
            variant="outline"
            onClick={() => setOpen(false)}
          >
            Cancel
          </Button>

          <Button
            onClick={handleGenerate}
            disabled={isPending}
          >
            {isPending ? "Generating..." : "Generate"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}